# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4c895485899f027ce7182857ea9558c42923ea1f27d7c70f9f789e8d02fd89fc12563c01ec2fa0254e36e25296c3518f7ff2c64c1319b0d9c1ff5abda84e669

test:
  secret_key_base: 661077c7d773fdfae7885950f4b2532d03892b5957dbb0457fb97ea3b4021420da8273a6394261b7d5100bc3d87411b464597879eed072417b30c7b8ea7d5699

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
